module.exports = [
  {
    gift_id: "",
    image: "essential-crew-neck.jpeg",
    price: 90,
    color: null,
    size: "Small",
    description: "The Essential Crew Neck is fit with a straight-fitting body, inset cuffed sleeves, and a classic crew neckline. Made from super soft, loopback terry, which is durable, breathable, and sleek. Features a straight fitting body and sleeves, and a slight drop shoulder.  Fit: Regular Male model is 5'9\" and wearing size medium. Female model is 5'4\" and wearing size small.",
    external_link: "https://shop.brainstation.io/collections/apparel/products/brainstation-essential-crew-neck",
  },
  {
    gift_id: "",
    image: "47-clean-up.jpeg",
    price: 40,
    color: null,
    size: null,
    description: "Relaxed and curved since 1947, the '47 CLEAN UP hat is one of our best-selling, signature silhouettes –– a favorite for fans and enthusiasts alike.  100% cotton Adjustable back fabric strap (one size fits most)",
    external_link: "https://shop.brainstation.io/collections/accessories/products/hat",
  },
  {
    gift_id: "",
    image: "klean-kanteen.jpeg",
    price: 42,
    color: null,
    size: null,
    description: "The best water bottle, coffee mug, sport bottle, and insulated cup in one package. Your Klean Kanteen is made from durable stainless steel and is designed to be lightweight yet extremely strong. If you take care of it, it may very well last your lifetime. The leakproof cap is made from BPA-free polypropylene and food-grade silicone. This cap is safe for use with acidic or hot beverages, making it the perfect cup for on the go.",
    external_link: "https://shop.brainstation.io/collections/accessories/products/brainstation-x-klean-kanteen",
  },
  {
    gift_id: "",
    image: "essential-tshirt-white.jpeg",
    price: 40,
    color: "White",
    size: "Small",
    description: "The Essential T-Shirt is slim-fitting through the body, and is crafted from soft and durable mid-weight 100% cotton jersey. Wash cold and lay flat to dry. We suggest sizing up one size if you plan to machine dry. Fit: Regular Male model is 5'9\" and wearing size medium. Female model is 5'9\" and wearing size small.",
    external_link: "https://shop.brainstation.io/collections/apparel/products/brainstation-essential-t-shirt-white",
  },
  {
    gift_id: "",
    image: "torrentshell.jpeg",
    price: 149,
    color: "Mulch Brown",
    size: "XS",
    description: "The best raincoat I've ever owned!",
    external_link: "https://www.patagonia.com/product/mens-torrentshell-3l-rain-jacket/85240.html?dwvar_85240_color=MULB&cgid=mens-new-jackets-vests",
  },
  {
    gift_id: "",
    image: "essential-tshirt-black.jpeg",
    price: 40,
    color: "Black",
    size: "Small",
    description: "The Essential T-Shirt is slim-fitting through the body, and is crafted from soft and durable mid-weight 100% cotton jersey. Wash cold and lay flat to dry. We suggest sizing up one size if you plan to machine dry. Fit: Regular  Female model is 5'8\" and wearing size small. Male model is 5'8\" and wearing size small.",
    external_link: "https://shop.brainstation.io/collections/apparel/products/brainstation-essential-t-shirt-black",
  },
  {
    gift_id: "",
    image: "neoskin-notebook.jpeg",
    price: 20,
    color: "Black",
    size: null,
    description: "A lined, soft cover, 128 page journal. You will find a small document holder on the back cover to store any important business cards or small papers. The paper colour is ivory, and is acid-free. Dimensions: 5.50\" x 8.25\"",
    external_link: "https://shop.brainstation.io/collections/accessories/products/neoskin-notebook",
  },
  {
    gift_id: "",
    image: "my-sticker-pack.jpeg",
    price: 4,
    color: null,
    size: null,
    description: "Share the love of your BrainStation experience with our custom, die cut stickers. Perfect for laptops, car windows, notebooks, or anywhere else you can think of. Made out of durable vinyl which protects your clear stickers from scratching, rain, and sunlight.",
    external_link: "https://shop.brainstation.io/collections/accessories/products/my-sticker-pack",
  },
];