module.exports = [
  {
    gift_id: "",
    image: "essential-crew-neck.jpeg",
    price: "90",
    color: null,
    size: null,
    description: null,
    external_link: "https://shop.brainstation.io/collections/apparel/products/brainstation-essential-crew-neck",
  },
  {
    gift_id: "",
    image: "47-clean-up.jpeg",
    price: "40",
    color: null,
    size: null,
    description: null,
    external_link: "https://shop.brainstation.io/collections/accessories/products/hat",
  },
  {
    gift_id: "",
    image: "klean-kanteen.jpeg",
    price: "42",
    color: null,
    size: null,
    description: null,
    external_link: "https://shop.brainstation.io/collections/accessories/products/brainstation-x-klean-kanteen",
  },
  {
    gift_id: "",
    image: "essential-tshirt-white.jpeg",
    price: "40",
    color: "White",
    size: null,
    description: null,
    external_link: "https://shop.brainstation.io/collections/apparel/products/brainstation-essential-t-shirt-white",
  },
  {
    gift_id: "",
    image: "essential-tshirt-black.jpeg",
    price: "40",
    color: "Black",
    size: null,
    description: null,
    external_link: "https://shop.brainstation.io/collections/apparel/products/brainstation-essential-t-shirt-black",
  },
  {
    gift_id: "",
    image: "neoskin-notebook.jpeg",
    price: "20",
    color: "Black",
    size: null,
    description: null,
    external_link: "https://shop.brainstation.io/collections/accessories/products/neoskin-notebook",
  },
  {
    gift_id: "",
    image: "my-sticker-pack.jpeg",
    price: "4",
    color: null,
    size: null,
    description: null,
    external_link: "https://shop.brainstation.io/collections/accessories/products/my-sticker-pack",
  },
];